repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
  - repo: local
    hooks:
      - id: formatters
        name: Run Isort and Black
        entry: make format
        language: python
        types: [python]
      - id: linter
        name: Run Flake8
        entry: make lint
        language: python
        types: [python]
